// Špeciálne kaviarne a bistrá v Ríme — curated podľa European Coffee Trip.
// https://europeancoffeetrip.com/rome/
export const FOOD = [
    {
        id: 'slow-roma',
        name: 'Slow — Specialty Coffee & Pastry Lab',
        type: 'cafe',
        coords: { lat: 41.8966, lon: 12.4737 },
        address: 'Corso Vittorio Emanuele II 73',
        area: 'Largo Argentina',
        description: 'Moderný specialty espresso bar a pekárna v historickom centre. Kvasnené croissanty, brunch a rýchle obedy.',
        source: 'European Coffee Trip',
    },
    {
        id: 'forno-conti',
        name: 'Forno Conti & Co.',
        type: 'bakery',
        coords: { lat: 41.8924, lon: 12.5031 },
        address: 'Via Giusti 18',
        area: 'Esquilino',
        description: 'Remeselná pekáreň s flaky croissantmi a sourdough chlebom. Matcha latte a starostlivo vybraný specialty coffee menu.',
        source: 'European Coffee Trip',
    },
    {
        id: 'grani-farine-caffe',
        name: 'Grani, Farine & Caffè',
        type: 'cafe',
        coords: { lat: 41.8838, lon: 12.4593 },
        address: 'Viale dei Quattro Venti 152',
        area: 'Monteverde',
        description: 'Malá specialty kaviareň bez typického baru — núti spomaliť a dať si čas. Výborné cornetti a sezónne raňajky.',
        source: 'European Coffee Trip',
    },
    {
        id: 'sensorio',
        name: 'Sensorio Coffee Lab',
        type: 'cafe',
        coords: { lat: 41.9133, lon: 12.4770 },
        address: 'Via Flaminia 69',
        area: 'Flaminio',
        description: 'Laboratórium so specialty espressom aj filtrom, ručne robené pečivo a brunch. Neďaleko Piazza del Popolo.',
        source: 'European Coffee Trip',
    },
    {
        id: 'forno-ritorno',
        name: 'Forno Ritorno',
        type: 'bakery',
        coords: { lat: 41.8800, lon: 12.4731 },
        address: 'Via Amerigo Vespucci 20',
        area: 'Testaccio',
        description: 'Moderná pekáreň s kvasnenou pizzou al taglio, croissantami a specialty kávou. Populárny hotspot v Testaccio.',
        source: 'European Coffee Trip',
    },
    {
        id: 'te-cioccolateria',
        name: 'TE Cioccolateria & TE Caffè',
        type: 'cafe',
        coords: { lat: 41.9055, lon: 12.4633 },
        address: 'Via Sforza Pallavicini 19',
        area: 'Prati (pri Vatikáne)',
        description: 'Čokoládovňa a kaviareň so severoeurópskou estetikou. Vynikajúce pralinky, torty a specialty coffee.',
        source: 'European Coffee Trip',
    },
    {
        id: 'mostro',
        name: 'Mostro',
        type: 'cafe',
        coords: { lat: 41.8773, lon: 12.4818 },
        address: 'Piazza di Porta San Paolo',
        area: 'Piramide / Ostiense',
        description: 'Maličký kiosk pri Pyramíde Cestia — specialty coffee cez deň, prírodné vína večer. Blízko nášho ubytovania.',
        source: 'European Coffee Trip',
    },
    {
        id: 'barnum-roma',
        name: 'Barnum Roma',
        type: 'cafe',
        coords: { lat: 41.8970, lon: 12.4700 },
        address: 'Via del Pellegrino 87',
        area: 'Campo de\' Fiori',
        description: 'Ikonická specialty kaviareň pri Campo de\' Fiori. Francúzske a severoeurópske pečivo, denný brunch. Očakávaj rad.',
        source: 'European Coffee Trip',
    },
];

window.__FOOD_DATA = FOOD;
